### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by mr337** [ruzin/terraform_aws_lambda_python#4]
Hi,

Testing to see if this project is abandoned. There are some changes that would be greatly appreciated via https://github.com/ruzin/terraform_aws_lambda_python/pull/2

**Comment by ruzin** [comment]
Not necessarily, what'd you have in mind?

**Comment by mr337** [comment]
Ha! It was mainly related to https://github.com/ruzin/terraform_aws_lambda_python/pull/2 which you already merged. Thanks!!!
